[package]
name = "kingdom-tycoon/project"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[place]
shared-packages = "game.ReplicatedStorage.Packages"
server-packages = "game.ServerScriptService.ServerPackages"

[dependencies]

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@=1.0.3"
